### ISSUE TITLE
Version 8.0.0 not on packagist

### ISSUE THREAD

**Issue by JorisOrangeStudio** [mattrothenberg/statamic-mapbox-address#10]
I'm unable to install the 8.0.0 version, since it is not found by packagist. Any idea why?
https://packagist.org/packages/mattrothenberg/statamic-mapbox-address

  Problem 1
    - Root composer.json requires mattrothenberg/statamic-mapbox-address ^8.0.0, found mattrothenberg/statamic-mapbox-address[dev-main, 0.1.0, ..., 0.7.4] but it does not match the constraint.

**Comment by mattrothenberg** [comment]
Apologies. This should be fixed now in 0.9.0

https://packagist.org/packages/mattrothenberg/statamic-mapbox-address
