### ISSUE TITLE
The slash is backwards in the installation instructions

### ISSUE THREAD

**Issue by austriker27** [mattrothenberg/statamic-mapbox-address#2]
Hi Matt, sweet addon! Just an FYI, i went to install it but got an error when running this per the readme: 

`composer require mattrothenberg\statamic-mapbox-address`

I believe it should be this, which works for me: 
`composer require mattrothenberg/statamic-mapbox-address`

Thanks again!

**Comment by mattrothenberg** [comment]
thanks @austriker27!

Feel free to submit a patch, given it's an easy tweak 😎
