### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by Lenitr** [mattrothenberg/statamic-mapbox-address#4]
Thanks for the addon, we've been testing with it for a bit and like the simplicity of it.

We're building a headless project, using GraphQL, and noticed that the addon doesn't support this feature yet.
I've already made some adjustments to the addon to add very basic GraphQL support (it just outputs all the data as an array).

Would it be possible to add a Pull request for this so you can review it? I've tried making one already but it seems I don't have permission to do this.

**Comment by mattrothenberg** [comment]
@Lenitr Of course! I'm not sure what you mean by it isn't possible to create a PR – there has already been a contribution via PR https://github.com/mattrothenberg/statamic-mapbox-address/pull/3

**Comment by Lenitr** [comment]
Sorry, that was my fault, I'm used to Bitbucket, not Github, I didn't realise I had to fork the project before I could create a pull request. It's done now.

**Comment by mattrothenberg** [comment]
Closed by #5
