### ISSUE TITLE
problems while installing

### ISSUE THREAD

**Issue by el-schneider** [mattrothenberg/statamic-mapbox-address#6]
Hi, 

I'm getting `Can't locate path: </app/vendor/mattrothenberg/statamic-mapbox-address/src/../dist/js/address.js>` within the install process. And also I'm not able to install `0.7.1`through composer. Do you know what the problem is?

Thanks for your work.

**Comment by mattrothenberg** [comment]
@el-schneider Odd. Can you please try again with `0.7.2`?

**Comment by el-schneider** [comment]
Thanks, everything is working now!
